- CHANGELOG.md
- project.clj
- src/dienstplan/commands.clj
- src/dienstplan/spec.clj
- test/dienstplan/commands_test.clj
> Remove team id form request context

- CHANGELOG.md
- README.md
- project.clj
- src/dienstplan/commands.clj
- src/dienstplan/db.clj
- test/dienstplan/commands_test.clj
> Support about command

- CHANGELOG.md
- project.clj
- src/dienstplan/core.clj
- src/dienstplan/middlewares.clj
> Fix default request uri

- CHANGELOG.md
- project.clj
- src/dienstplan/commands.clj
- src/dienstplan/db.clj
- src/dienstplan/slack.clj
- src/dienstplan/spec.clj
- test/dienstplan/commands_test.clj
- test/dienstplan/db_test.clj
- test/dienstplan/slack_test.clj
> Rotate command to show previous and current oncall persons

- CHANGELOG.md
- project.clj
- src/dienstplan/commands.clj
- src/dienstplan/endpoints.clj
- src/dienstplan/slack.clj
- src/dienstplan/spec.clj
- src/dienstplan/verify.clj
- test/dienstplan/commands_test.clj
- test/dienstplan/endpoints_test.clj
- test/dienstplan/slack_test.clj
- test/dienstplan/verify_test.clj
> Functions speccing and instrumenting

- .gitignore
- CHANGELOG.md
- README.md
- project.clj
- src/dienstplan/commands.clj
- src/dienstplan/db.clj
- src/dienstplan/spec.clj
- test/dienstplan/commands_test.clj
- test/dienstplan/db_test.clj
Link to the [issue](https://github.com/pilosus/dienstplan/issues/36)
> Feature: assign command #36

- CHANGELOG.md
- project.clj
- src/dienstplan/commands.clj
- src/dienstplan/spec.clj
- test/dienstplan/commands_test.clj
> Rename rotation name command arg kw

- CHANGELOG.md
- project.clj
- src/dienstplan/commands.clj
- src/dienstplan/spec.clj
- test/dienstplan/commands_test.clj
> Fix NPE for create and assign

- CHANGELOG.md
- project.clj
- src/dienstplan/commands.clj
- test/dienstplan/commands_test.clj
> Show app version in help message

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
> Contributing guide and other community docs

- CHANGELOG.md
- project.clj
- test/dienstplan/api_test.clj
> Refactor integration tests

- CHANGELOG.md
- README.md
- project.clj
- src/dienstplan/commands.clj
- test/dienstplan/api_test.clj
- test/dienstplan/commands_test.clj
> Shout command used to mention current on-call person only with duties description omitted

- .dockerignore
- CHANGELOG.md
- Dockerfile
- Dockerfile-test
- README.md
- docker-compose.yml
- project.clj
> Reduce docker container size

- CHANGELOG.md
- src/dienstplan/commands.clj
> Usage example for assign command fixed

- LICENSE
- README.md
- src/dienstplan/commands.clj
- src/dienstplan/config.clj
- src/dienstplan/core.clj
- src/dienstplan/db.clj
- src/dienstplan/endpoints.clj
- src/dienstplan/logging.clj
- src/dienstplan/middlewares.clj
- src/dienstplan/slack.clj
- src/dienstplan/spec.clj
- src/dienstplan/verify.clj
- test/dienstplan/api_test.clj
- test/dienstplan/commands_test.clj
- test/dienstplan/core_test.clj
- test/dienstplan/db_test.clj
- test/dienstplan/endpoints_test.clj
- test/dienstplan/slack_test.clj
- test/dienstplan/verify_test.clj
> Remove copyright years where unnecessary

- CHANGELOG.md
- Dockerfile
- Makefile
- deps.edn
- docs/install.md
- resources/dienstplan/config.yaml
- resources/logback.json.xml
- resources/logback.xml
- src/dienstplan/middlewares.clj
- src/dienstplan/spec.clj
> Separate root and app logger levels; add JSON logging

- .env
- CHANGELOG.md
- Makefile
- README.md
- build.clj
- deps.edn
- docs/index.md
- docs/install.md
- docs/usage.md
- resources/logback.xml
- resources/migrations/0003-schedule.edn
- src/dienstplan/commands.clj
- src/dienstplan/core.clj
- src/dienstplan/db.clj
- src/dienstplan/helpers.clj
- src/dienstplan/middlewares.clj
- src/dienstplan/schedule.clj
- src/dienstplan/spec.clj
- src/dienstplan/verify.clj
- test/dienstplan/api_test.clj
- test/dienstplan/commands_test.clj
- test/dienstplan/fixture.clj
- test/dienstplan/helpers_test.clj
- test/dienstplan/verify_test.clj
> Events scheduling based on crontab format strings

- CHANGELOG.md
- resources/logback.xml
- src/dienstplan/commands.clj
- src/dienstplan/schedule.clj
- src/dienstplan/spec.clj
> Explicit schedule execution

- CHANGELOG.md
- Makefile
- deps.edn
- docs/install.md
- resources/dienstplan/config.yaml
- src/dienstplan/core.clj
- src/dienstplan/schedule.clj
- src/dienstplan/spec.clj
> Daemonize scheduling

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile-test
- deps.edn
- src/dienstplan/schedule.clj
> Update to Java 21, bump deps

- compose.yml
Dockre compose config file updated to match compose specification. Local database updated to PG 16.2 (don't forget to remote local data directory!)
> chore: move docker compose config v3 to compose specification

- deps.edn
> chore: bump dependencies

- CHANGELOG.md
- src/dienstplan/commands.clj
- test/dienstplan/api_test.clj
- test/dienstplan/commands_test.clj
Slack user groups (subteams) are supported.
Closes https://github.com/pilosus/dienstplan/issues/115
> feat: support Slack user groups
